/**
 * GAME CONFIG - Uses Central Configuration
 * This file provides backward compatibility while using the central config
 */

import CentralConfig from './CentralConfig';

const { ENTITY_LIMITS, PHYSICS, FLOCKING, VISUALS, SIZES, TIMING, SCORING, WAVES } = CentralConfig;

export const GameConfig = {
  // Flocking parameters - FROM CENTRAL CONFIG
  VIEW_RADIUS: FLOCKING.RADIUS.VIEW,
  SEPARATION_RADIUS: FLOCKING.RADIUS.SEPARATION,
  BOID_SIZE: SIZES.BIRD.BASE,
  BASE_SPEED: PHYSICS.SPEED.BASE_BIRD_SPEED,
  BASE_FORCE: PHYSICS.SPEED.BASE_BIRD_FORCE,
  
  // Flocking weights - FROM CENTRAL CONFIG
  WEIGHT_SEPARATION: FLOCKING.WEIGHTS.SEPARATION,
  WEIGHT_ALIGNMENT: FLOCKING.WEIGHTS.ALIGNMENT,
  WEIGHT_COHESION: FLOCKING.WEIGHTS.COHESION,
  WEIGHT_TARGET: FLOCKING.WEIGHTS.TARGET,
  WEIGHT_AVOID: FLOCKING.WEIGHTS.AVOID,
  
  // Game mechanics - FROM CENTRAL CONFIG
  ENERGY_COUNT: ENTITY_LIMITS.ENERGY_DOTS.TOTAL_COUNT,
  ENERGY_RADIUS: SIZES.ENERGY_DOT.RADIUS,
  BASE_Y: 0.85, // Position of energy dots (85% down the screen)
  
  // Respawn timers - FROM CENTRAL CONFIG
  DOT_RESPAWN_BASE: TIMING.DOT_RESPAWN_DELAY_MS,
  DOT_RESPAWN_PER_WAVE: -300, // Faster by 0.3s per wave
  DOT_RESPAWN_MIN: 3000, // Never faster than 3 seconds
  
  // Asteroids - FROM CENTRAL CONFIG
  AST_MIN: SIZES.ASTEROID.MIN,
  AST_MAX: SIZES.ASTEROID.MAX,
  AST_SPEED: PHYSICS.SPEED.ASTEROID_BASE_SPEED,
  AST_GROWTH_RATE: SIZES.ASTEROID.CHARGE_GROWTH_RATE,
  AST_MAX_CHARGE: SIZES.ASTEROID.MAX_CHARGE_SIZE,
  AST_SLOWNESS_FACTOR: 0.3, // BIG asteroids are 70% slower!
  
  // Progression - Extended wave config
  BIRDS_PER_WAVE: [
    2, 3, 4, 5, 6, 7, 8, 9, 10, 11, // Waves 1-10: gentle start
    12, 13, 14, 16, 18, 20, 22, 24, 26, 28, // Waves 11-20: moderate
    30, 32, 35, 38, 41, 44, 47, 50, 54, 58, // Waves 21-30: challenging
    62, 66, 70, 75, 80, 85, 90, 96, 102, 108, // Waves 31-40: hard
    115, 122, 130, 138, 146, 155, 164, 174, 184, 195, // Waves 41-50: very hard
    206, 218, 230, 243, 256, 270, 285, 300, 316, 333  // Waves 51-60: extreme
  ],
  SPEED_GROWTH: WAVES.SPEED_GROWTH,
  BOSS_WAVE_INTERVAL: WAVES.BOSS_WAVE_INTERVAL,
  
  // Visual - FROM CENTRAL CONFIG
  NEON_COLORS: [
    VISUALS.COLORS.NEON_MAGENTA,
    VISUALS.COLORS.NEON_CYAN,
    VISUALS.COLORS.NEON_YELLOW,
    VISUALS.COLORS.NEON_RED,
    VISUALS.COLORS.NEON_GREEN,
    VISUALS.COLORS.NEON_ORANGE,
    VISUALS.COLORS.NEON_BLUE,
    VISUALS.COLORS.NEON_PURPLE,
  ],
  
  // Performance - FROM CENTRAL CONFIG
  MAX_PARTICLES: ENTITY_LIMITS.PARTICLES.MAX_TOTAL,
  PARTICLE_LIFETIME: 1.0,
  
  // Scoring - FROM CENTRAL CONFIG
  SCORE_HIT: SCORING.POINTS.BIRD_HIT,
  SCORE_COMBO_2: 25,
  SCORE_COMBO_3: 50,
  SCORE_COMBO_4: 100,
  SCORE_CLEVER: 200, // ricochet kills
  SCORE_DOT_SAVED: SCORING.POINTS.DOT_SAVED,
} as const;